In [1]:
import numpy as np

### 1. Создайте вектор с элементами от 12 до 42

In [2]:
vector1 = np.arange(12, 43)
vector1

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42])

### 2. Создайте вектор из нулей длины 12, но его пятый элемент должен быть равен 1

In [3]:
vector2 = np.zeros(12)
vector2[4] = 1
vector2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

### 3. Создайте матрицу (3, 3), заполненную от 0 до 8

In [4]:
matrix = np.arange(9).reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 4. Найдите все положительные числа в np.array([1,2,0,0,4,0])

In [5]:
array = np.array([1, 2, 0, 0, 4, 0])
array[array > 0]

array([1, 2, 4])

### 5. Умножьте матрицу размерности (5, 3) на (3, 2)

In [6]:
matrix1 = np.random.rand(5, 3)
matrix2 = np.random.rand(3, 2)
result = np.dot(matrix1, matrix2)
result

array([[1.55093325, 1.08556586],
       [1.26407136, 0.68423499],
       [1.37052221, 1.03373819],
       [0.80564384, 0.53643167],
       [0.13766095, 0.08513556]])

### 6. Создайте матрицу (10, 10) так, чтобы на границе были 0, а внутри 1

In [7]:
matrix_boundary = np.zeros((10, 10))
matrix_boundary[1:-1, 1:-1] = 1
matrix_boundary

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### 7. Создайте рандомный вектор и отсортируйте его

In [8]:
random_vector = np.random.rand(10)
np.sort(random_vector)

array([0.1294494 , 0.13332755, 0.1787221 , 0.42448732, 0.51931482,
       0.58136596, 0.59443267, 0.69283501, 0.72696109, 0.96318298])

### 8. Каков эквивалент функции enumerate для numpy массивов?

In [9]:
array = np.array([10, 20, 30, 32, 2, 1])
for index, value in np.ndenumerate(array):
    print(index, value)

(0,) 10
(1,) 20
(2,) 30
(3,) 32
(4,) 2
(5,) 1


### 9. Создайте рандомную матрицу и выполните нормализацию столбцов

In [10]:
random_matrix = np.random.rand(5, 3)
normalized_matrix = (random_matrix - np.mean(random_matrix, axis=0))
normalized_matrix = normalized_matrix / np.std(normalized_matrix, axis=0)
normalized_matrix

array([[ 1.25678471,  0.52859088, -1.02839725],
       [ 0.93697397,  0.0381923 ,  1.19418559],
       [ 0.0595554 ,  1.47034459, -1.34597167],
       [-1.1391659 , -0.52750634,  0.6543714 ],
       [-1.11414819, -1.50962143,  0.52581193]])

### 10. Для заданного числа найдите ближайший к нему элемент в векторе

In [11]:
number = 0.5
vector = np.random.rand(10)
print(vector)
closest_value = vector[np.abs(vector - number).argmin()]
closest_value

[0.44356718 0.23114639 0.40790918 0.2849821  0.80838434 0.87354636
 0.09213713 0.98447508 0.84700177 0.35794858]


0.4435671799984233

### 11. Найдите N наибольших значений в векторе

In [12]:
N = 3
vector = np.random.rand(10)
print(vector)
largest_values = vector[np.argsort(vector)[-N:]]
largest_values

[0.1817758  0.37695889 0.16833064 0.98977828 0.97009399 0.22211787
 0.75709755 0.88847429 0.6066234  0.06861746]


array([0.88847429, 0.97009399, 0.98977828])